version: '2.1'
networks:
  dev:
    driver: bridge
volumes:
  conf: {}
  data: {}
  logs: {}
services:
  sonar:
    image: sonarqube:7.9.1-community
    ports: ['80:9000']
    networks: [dev]
    volumes: ['conf:/opt/sonarqube/conf',
              'data:/opt/sonarqube/data',
              'logs:/opt/sonarqube/logs',]
    healthcheck:
      test: curl -f http://127.0.0.1:9000/ || exit 1
      interval: 5s
      retries: 25
